---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${PROJECT_NAME}-resource-limit
# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: ${PROJECT_NAME}-resource-limit-high
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${PROJECT_NAME}-resource-counts
