apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-2048
spec:
  template:
    spec:
      containers:
      - name: docker-2048
        resources:
          limits:
            memory: 1.5Gi
            cpu: 1
          requests:
            memory: 64Mi
            cpu: 10m
