---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-demo-resource-limit
# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: app-demo-resource-limit-high
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-demo-resource-counts
