# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-cm
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: argocd-cm
#     app.kubernetes.io/part-of: argocd
# data:
#     kustomize.version.v3.8.7: /custom-tools/kustomize_3_8_7
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-2048
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/currycan/kustomize.git
    targetRevision: master
    path: overlays/prod
    # kustomize:
    #   version: v3.8.7
  destination:
    server: https://kubernetes.default.svc
    namespace: app-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
