---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-2048
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/currycan/kustomize.git
    targetRevision: v0.0.1
    path: overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    kustomize:
      version: v3.8.7
