apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_DEMO_NAME}
spec:
  template:
    metadata:
      labels:
        app: kaolabao-agent
    spec:
      containers:
      - name: ${APP_DEMO_NAME}
      imagePullSecrets:
        - name: lkl-zf-ss-cdmp-sit
