apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ${PROJECT_NAME}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
