apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-2048
spec:
  template:
    spec:
      containers:
      - name: docker-2048
        resources:
          limits:
            memory: 512Gi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 10m
