apiVersion: v1
kind: Service
metadata:
  name: ${APP_DEMO_NAME}
spec:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: http-80
  selector:
    app: ${APP_DEMO_NAME}
  type: LoadBalancer
