apiVersion: v1
kind: Service
metadata:
  name: docker-2048
spec:
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: http-80
  selector:
    app: docker-2048
  type: LoadBalancer
