apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s3.small
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
  name: ${APP_DEMO_NAME}
  labels:
    app: ${APP_DEMO_NAME}
spec:
  externalTrafficPolicy: Local
  publishNotReadyAddresses: true
  # type: ClusterIP
  type: LoadBalancer
